version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  aws-cli: circleci/aws-cli@0.1.18
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      # - run: npm run lint
      # - run: npm run e2e
      - run: npm run build
      # Persist entire project directory to the next job
      - persist_to_workspace:
          root: .
          paths: .
      - run: exit 0
      - slack/status:
          mentions: 'A018EEQR020'
          success_message: '[${PROJECT_ENV_VAR}]Build success! :bb-dance::pet-bb-head::bb-begging:'
          failure_message: '[${PROJECT_ENV_VAR}]Build failed! :bb-no::bb-panggang-no-cry::bb-emo-bb-cry::bb-cry-till-flood:'

  deploy:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Deploy entire directory
          command: aws s3 cp ./build s3://bb-reader-bucket --recursive
      - slack/status:
          mentions: 'A018EEQR020'
          success_message: '[${PROJECT_ENV_VAR}]Deploy success! :bb-dance::pet-bb-head::bb-begging:'
          failure_message: '[${PROJECT_ENV_VAR}]Deploy failed! :bb-no::bb-panggang-no-cry::bb-emo-bb-cry::bb-cry-till-flood:'
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          context: aws
          filters:
           branches:
             only: master    
